// goagent AgentService gRPC协议定义
// 为IM系统提供智能Agent能力

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: agent.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============================================================
// 消息处理
// ============================================================
type ProcessMessageReq struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	UserId    int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 发送者用户ID
	TargetId  int32                  `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // 目标ID（单聊时为对方用户ID，群聊时为群ID）
	Content   string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                    // 消息文本内容（用户输入给Agent的指令）
	ChatType  int32                  `protobuf:"varint,4,opt,name=chat_type,json=chatType,proto3" json:"chat_type,omitempty"` // 聊天类型：1=单聊, 2=群聊
	Timestamp int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`               // 消息时间戳（毫秒）
	Model     string                 `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`                        // 可选：指定使用的模型名称，为空则使用默认模型
	// ── 方式B：技能分发 ──
	// skill 为空或 "chat" 时走普通对话；其余值触发对应技能（不同系统提示词）。
	// 已支持: "summarize"(聊天总结) / "suggest_reply"(智能回复建议)。
	// 新增技能只需在 GoAgent 内部扩展，proto/IMServer/客户端无需改结构。
	Skill string `protobuf:"bytes,7,opt,name=skill,proto3" json:"skill,omitempty"` // 技能标识，空=普通对话
	// context 携带该技能所需的上下文消息（如要总结/参考的历史聊天），
	// 由客户端从本地聊天缓存打包传入，GoAgent 保持无状态。
	Context       []string `protobuf:"bytes,8,rep,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessMessageReq) Reset() {
	*x = ProcessMessageReq{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMessageReq) ProtoMessage() {}

func (x *ProcessMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMessageReq.ProtoReflect.Descriptor instead.
func (*ProcessMessageReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessMessageReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ProcessMessageReq) GetTargetId() int32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *ProcessMessageReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ProcessMessageReq) GetChatType() int32 {
	if x != nil {
		return x.ChatType
	}
	return 0
}

func (x *ProcessMessageReq) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ProcessMessageReq) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ProcessMessageReq) GetSkill() string {
	if x != nil {
		return x.Skill
	}
	return ""
}

func (x *ProcessMessageReq) GetContext() []string {
	if x != nil {
		return x.Context
	}
	return nil
}

type ProcessMessageRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`  // 0=成功, 非0=错误
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`     // 提示信息（成功或错误描述）
	Reply         string                 `protobuf:"bytes,3,opt,name=reply,proto3" json:"reply,omitempty"` // Agent生成的回复内容
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"` // 实际使用的模型名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessMessageRsp) Reset() {
	*x = ProcessMessageRsp{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessMessageRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMessageRsp) ProtoMessage() {}

func (x *ProcessMessageRsp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMessageRsp.ProtoReflect.Descriptor instead.
func (*ProcessMessageRsp) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessMessageRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ProcessMessageRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ProcessMessageRsp) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *ProcessMessageRsp) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

// ============================================================
// 健康检查
// ============================================================
type HealthCheckReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckReq) Reset() {
	*x = HealthCheckReq{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckReq) ProtoMessage() {}

func (x *HealthCheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckReq.ProtoReflect.Descriptor instead.
func (*HealthCheckReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

type HealthCheckRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`                     // 整体是否健康（服务自身正常 + LLM可用）
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                      // 服务版本号
	LlmStatus     string                 `protobuf:"bytes,3,opt,name=llm_status,json=llmStatus,proto3" json:"llm_status,omitempty"` // LLM Provider状态: "active" / "empty" / "error"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRsp) Reset() {
	*x = HealthCheckRsp{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRsp) ProtoMessage() {}

func (x *HealthCheckRsp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRsp.ProtoReflect.Descriptor instead.
func (*HealthCheckRsp) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckRsp) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckRsp) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckRsp) GetLlmStatus() string {
	if x != nil {
		return x.LlmStatus
	}
	return ""
}

// ============================================================
// 模型列表
// ============================================================
type ListModelsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsReq) Reset() {
	*x = ListModelsReq{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsReq) ProtoMessage() {}

func (x *ListModelsReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsReq.ProtoReflect.Descriptor instead.
func (*ListModelsReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

type ListModelsRsp struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Models        []*ListModelsRsp_ModelInfo `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"` // 可用模型列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRsp) Reset() {
	*x = ListModelsRsp{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRsp) ProtoMessage() {}

func (x *ListModelsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRsp.ProtoReflect.Descriptor instead.
func (*ListModelsRsp) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ListModelsRsp) GetModels() []*ListModelsRsp_ModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

// ============================================================
// VIP 升级 / 状态
// ============================================================
type UpgradeVipReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                  // 待升级用户ID
	PaymentToken  string                 `protobuf:"bytes,2,opt,name=payment_token,json=paymentToken,proto3" json:"payment_token,omitempty"` // 支付凭证（真实支付网关返回；当前为模拟令牌）
	AmountCents   int32                  `protobuf:"varint,3,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`   // 支付金额（分），VIP 为 500（$5）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeVipReq) Reset() {
	*x = UpgradeVipReq{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeVipReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeVipReq) ProtoMessage() {}

func (x *UpgradeVipReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeVipReq.ProtoReflect.Descriptor instead.
func (*UpgradeVipReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *UpgradeVipReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpgradeVipReq) GetPaymentToken() string {
	if x != nil {
		return x.PaymentToken
	}
	return ""
}

func (x *UpgradeVipReq) GetAmountCents() int32 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

type VipStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VipStatusReq) Reset() {
	*x = VipStatusReq{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VipStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VipStatusReq) ProtoMessage() {}

func (x *VipStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VipStatusReq.ProtoReflect.Descriptor instead.
func (*VipStatusReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *VipStatusReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type VipStatusRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                // 0=成功, 非0=失败
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`                   // 提示信息
	IsVip         bool                   `protobuf:"varint,3,opt,name=is_vip,json=isVip,proto3" json:"is_vip,omitempty"` // 当前是否为 VIP
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VipStatusRsp) Reset() {
	*x = VipStatusRsp{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VipStatusRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VipStatusRsp) ProtoMessage() {}

func (x *VipStatusRsp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VipStatusRsp.ProtoReflect.Descriptor instead.
func (*VipStatusRsp) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *VipStatusRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *VipStatusRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *VipStatusRsp) GetIsVip() bool {
	if x != nil {
		return x.IsVip
	}
	return false
}

type ListModelsRsp_ModelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                             // 模型名称，如 "gpt-4o", "claude-opus-4-8"
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`                     // 所属Provider，如 "openai", "anthropic"
	MaxTokens     int32                  `protobuf:"varint,3,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"` // 最大输出token数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRsp_ModelInfo) Reset() {
	*x = ListModelsRsp_ModelInfo{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRsp_ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRsp_ModelInfo) ProtoMessage() {}

func (x *ListModelsRsp_ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRsp_ModelInfo.ProtoReflect.Descriptor instead.
func (*ListModelsRsp_ModelInfo) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ListModelsRsp_ModelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListModelsRsp_ModelInfo) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ListModelsRsp_ModelInfo) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x05agent\"\xe4\x01\n" +
	"\x11ProcessMessageReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x05R\btargetId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tchat_type\x18\x04 \x01(\x05R\bchatType\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05model\x18\x06 \x01(\tR\x05model\x12\x14\n" +
	"\x05skill\x18\a \x01(\tR\x05skill\x12\x18\n" +
	"\acontext\x18\b \x03(\tR\acontext\"e\n" +
	"\x11ProcessMessageRsp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x14\n" +
	"\x05reply\x18\x03 \x01(\tR\x05reply\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\"\x10\n" +
	"\x0eHealthCheckReq\"c\n" +
	"\x0eHealthCheckRsp\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"llm_status\x18\x03 \x01(\tR\tllmStatus\"\x0f\n" +
	"\rListModelsReq\"\xa3\x01\n" +
	"\rListModelsRsp\x126\n" +
	"\x06models\x18\x01 \x03(\v2\x1e.agent.ListModelsRsp.ModelInfoR\x06models\x1aZ\n" +
	"\tModelInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x03 \x01(\x05R\tmaxTokens\"p\n" +
	"\rUpgradeVipReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12#\n" +
	"\rpayment_token\x18\x02 \x01(\tR\fpaymentToken\x12!\n" +
	"\famount_cents\x18\x03 \x01(\x05R\vamountCents\"'\n" +
	"\fVipStatusReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"K\n" +
	"\fVipStatusRsp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x15\n" +
	"\x06is_vip\x18\x03 \x01(\bR\x05isVip2\xbe\x02\n" +
	"\fAgentService\x12D\n" +
	"\x0eProcessMessage\x12\x18.agent.ProcessMessageReq\x1a\x18.agent.ProcessMessageRsp\x12;\n" +
	"\vHealthCheck\x12\x15.agent.HealthCheckReq\x1a\x15.agent.HealthCheckRsp\x128\n" +
	"\n" +
	"ListModels\x12\x14.agent.ListModelsReq\x1a\x14.agent.ListModelsRsp\x127\n" +
	"\n" +
	"UpgradeVip\x12\x14.agent.UpgradeVipReq\x1a\x13.agent.VipStatusRsp\x128\n" +
	"\fGetVipStatus\x12\x13.agent.VipStatusReq\x1a\x13.agent.VipStatusRspB\x10Z\x0egoagent/pkg/pbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_agent_proto_goTypes = []any{
	(*ProcessMessageReq)(nil),       // 0: agent.ProcessMessageReq
	(*ProcessMessageRsp)(nil),       // 1: agent.ProcessMessageRsp
	(*HealthCheckReq)(nil),          // 2: agent.HealthCheckReq
	(*HealthCheckRsp)(nil),          // 3: agent.HealthCheckRsp
	(*ListModelsReq)(nil),           // 4: agent.ListModelsReq
	(*ListModelsRsp)(nil),           // 5: agent.ListModelsRsp
	(*UpgradeVipReq)(nil),           // 6: agent.UpgradeVipReq
	(*VipStatusReq)(nil),            // 7: agent.VipStatusReq
	(*VipStatusRsp)(nil),            // 8: agent.VipStatusRsp
	(*ListModelsRsp_ModelInfo)(nil), // 9: agent.ListModelsRsp.ModelInfo
}
var file_agent_proto_depIdxs = []int32{
	9, // 0: agent.ListModelsRsp.models:type_name -> agent.ListModelsRsp.ModelInfo
	0, // 1: agent.AgentService.ProcessMessage:input_type -> agent.ProcessMessageReq
	2, // 2: agent.AgentService.HealthCheck:input_type -> agent.HealthCheckReq
	4, // 3: agent.AgentService.ListModels:input_type -> agent.ListModelsReq
	6, // 4: agent.AgentService.UpgradeVip:input_type -> agent.UpgradeVipReq
	7, // 5: agent.AgentService.GetVipStatus:input_type -> agent.VipStatusReq
	1, // 6: agent.AgentService.ProcessMessage:output_type -> agent.ProcessMessageRsp
	3, // 7: agent.AgentService.HealthCheck:output_type -> agent.HealthCheckRsp
	5, // 8: agent.AgentService.ListModels:output_type -> agent.ListModelsRsp
	8, // 9: agent.AgentService.UpgradeVip:output_type -> agent.VipStatusRsp
	8, // 10: agent.AgentService.GetVipStatus:output_type -> agent.VipStatusRsp
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
