// goagent AgentService gRPC协议定义
// 为IM系统提供智能Agent能力

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: agent.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_ProcessMessage_FullMethodName = "/agent.AgentService/ProcessMessage"
	AgentService_HealthCheck_FullMethodName    = "/agent.AgentService/HealthCheck"
	AgentService_ListModels_FullMethodName     = "/agent.AgentService/ListModels"
	AgentService_UpgradeVip_FullMethodName     = "/agent.AgentService/UpgradeVip"
	AgentService_GetVipStatus_FullMethodName   = "/agent.AgentService/GetVipStatus"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ============================================================
// AgentService — IM Agent的gRPC服务接口
// IMServer作为客户端，将用户消息转发给Agent处理
// Agent返回生成的回复，IMServer负责投递回IM会话
// ============================================================
type AgentServiceClient interface {
	// 处理消息 — IMServer转发用户消息到Agent，获取AI回复
	ProcessMessage(ctx context.Context, in *ProcessMessageReq, opts ...grpc.CallOption) (*ProcessMessageRsp, error)
	// 健康检查 — 检测Agent服务及下游LLM Provider是否可用
	HealthCheck(ctx context.Context, in *HealthCheckReq, opts ...grpc.CallOption) (*HealthCheckRsp, error)
	// 获取模型列表 — 返回当前Provider支持的模型
	ListModels(ctx context.Context, in *ListModelsReq, opts ...grpc.CallOption) (*ListModelsRsp, error)
	// 升级 VIP — 校验支付后将用户标记为 VIP（享更高 AI 配额）
	UpgradeVip(ctx context.Context, in *UpgradeVipReq, opts ...grpc.CallOption) (*VipStatusRsp, error)
	// 查询 VIP 状态
	GetVipStatus(ctx context.Context, in *VipStatusReq, opts ...grpc.CallOption) (*VipStatusRsp, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) ProcessMessage(ctx context.Context, in *ProcessMessageReq, opts ...grpc.CallOption) (*ProcessMessageRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessMessageRsp)
	err := c.cc.Invoke(ctx, AgentService_ProcessMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) HealthCheck(ctx context.Context, in *HealthCheckReq, opts ...grpc.CallOption) (*HealthCheckRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckRsp)
	err := c.cc.Invoke(ctx, AgentService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListModels(ctx context.Context, in *ListModelsReq, opts ...grpc.CallOption) (*ListModelsRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsRsp)
	err := c.cc.Invoke(ctx, AgentService_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) UpgradeVip(ctx context.Context, in *UpgradeVipReq, opts ...grpc.CallOption) (*VipStatusRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VipStatusRsp)
	err := c.cc.Invoke(ctx, AgentService_UpgradeVip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetVipStatus(ctx context.Context, in *VipStatusReq, opts ...grpc.CallOption) (*VipStatusRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VipStatusRsp)
	err := c.cc.Invoke(ctx, AgentService_GetVipStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// ============================================================
// AgentService — IM Agent的gRPC服务接口
// IMServer作为客户端，将用户消息转发给Agent处理
// Agent返回生成的回复，IMServer负责投递回IM会话
// ============================================================
type AgentServiceServer interface {
	// 处理消息 — IMServer转发用户消息到Agent，获取AI回复
	ProcessMessage(context.Context, *ProcessMessageReq) (*ProcessMessageRsp, error)
	// 健康检查 — 检测Agent服务及下游LLM Provider是否可用
	HealthCheck(context.Context, *HealthCheckReq) (*HealthCheckRsp, error)
	// 获取模型列表 — 返回当前Provider支持的模型
	ListModels(context.Context, *ListModelsReq) (*ListModelsRsp, error)
	// 升级 VIP — 校验支付后将用户标记为 VIP（享更高 AI 配额）
	UpgradeVip(context.Context, *UpgradeVipReq) (*VipStatusRsp, error)
	// 查询 VIP 状态
	GetVipStatus(context.Context, *VipStatusReq) (*VipStatusRsp, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) ProcessMessage(context.Context, *ProcessMessageReq) (*ProcessMessageRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessMessage not implemented")
}
func (UnimplementedAgentServiceServer) HealthCheck(context.Context, *HealthCheckReq) (*HealthCheckRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedAgentServiceServer) ListModels(context.Context, *ListModelsReq) (*ListModelsRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedAgentServiceServer) UpgradeVip(context.Context, *UpgradeVipReq) (*VipStatusRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpgradeVip not implemented")
}
func (UnimplementedAgentServiceServer) GetVipStatus(context.Context, *VipStatusReq) (*VipStatusRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVipStatus not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_ProcessMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ProcessMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ProcessMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ProcessMessage(ctx, req.(*ProcessMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).HealthCheck(ctx, req.(*HealthCheckReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListModels(ctx, req.(*ListModelsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_UpgradeVip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeVipReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).UpgradeVip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_UpgradeVip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).UpgradeVip(ctx, req.(*UpgradeVipReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetVipStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VipStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetVipStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetVipStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetVipStatus(ctx, req.(*VipStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessMessage",
			Handler:    _AgentService_ProcessMessage_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _AgentService_HealthCheck_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _AgentService_ListModels_Handler,
		},
		{
			MethodName: "UpgradeVip",
			Handler:    _AgentService_UpgradeVip_Handler,
		},
		{
			MethodName: "GetVipStatus",
			Handler:    _AgentService_GetVipStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}
