// GoImageServer — 头像微服务 gRPC 协议
// 业务操作（上传/删除/查询）走 gRPC+Protobuf
// 图片获取走 HTTP 静态文件服务（QML Image 组件需要 URL）

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: avatar.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommonRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonRsp) Reset() {
	*x = CommonRsp{}
	mi := &file_avatar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonRsp) ProtoMessage() {}

func (x *CommonRsp) ProtoReflect() protoreflect.Message {
	mi := &file_avatar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonRsp.ProtoReflect.Descriptor instead.
func (*CommonRsp) Descriptor() ([]byte, []int) {
	return file_avatar_proto_rawDescGZIP(), []int{0}
}

func (x *CommonRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommonRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UploadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ImageData     []byte                 `protobuf:"bytes,2,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"` // "png" / "jpg" / "gif" / "webp"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadReq) Reset() {
	*x = UploadReq{}
	mi := &file_avatar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadReq) ProtoMessage() {}

func (x *UploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_avatar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadReq.ProtoReflect.Descriptor instead.
func (*UploadReq) Descriptor() ([]byte, []int) {
	return file_avatar_proto_rawDescGZIP(), []int{1}
}

func (x *UploadReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UploadReq) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *UploadReq) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type UploadRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"` // 服务器上存储的文件名
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`           // 完整访问URL (http://IP:8080/avatars/xxx.png)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRsp) Reset() {
	*x = UploadRsp{}
	mi := &file_avatar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRsp) ProtoMessage() {}

func (x *UploadRsp) ProtoReflect() protoreflect.Message {
	mi := &file_avatar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRsp.ProtoReflect.Descriptor instead.
func (*UploadRsp) Descriptor() ([]byte, []int) {
	return file_avatar_proto_rawDescGZIP(), []int{2}
}

func (x *UploadRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UploadRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *UploadRsp) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadRsp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type DeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReq) Reset() {
	*x = DeleteReq{}
	mi := &file_avatar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReq) ProtoMessage() {}

func (x *DeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_avatar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReq.ProtoReflect.Descriptor instead.
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return file_avatar_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUrlReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUrlReq) Reset() {
	*x = GetUrlReq{}
	mi := &file_avatar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUrlReq) ProtoMessage() {}

func (x *GetUrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_avatar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUrlReq.ProtoReflect.Descriptor instead.
func (*GetUrlReq) Descriptor() ([]byte, []int) {
	return file_avatar_proto_rawDescGZIP(), []int{4}
}

func (x *GetUrlReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUrlRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUrlRsp) Reset() {
	*x = GetUrlRsp{}
	mi := &file_avatar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUrlRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUrlRsp) ProtoMessage() {}

func (x *GetUrlRsp) ProtoReflect() protoreflect.Message {
	mi := &file_avatar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUrlRsp.ProtoReflect.Descriptor instead.
func (*GetUrlRsp) Descriptor() ([]byte, []int) {
	return file_avatar_proto_rawDescGZIP(), []int{5}
}

func (x *GetUrlRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetUrlRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetUrlRsp) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *GetUrlRsp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type HealthCheckReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckReq) Reset() {
	*x = HealthCheckReq{}
	mi := &file_avatar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckReq) ProtoMessage() {}

func (x *HealthCheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_avatar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckReq.ProtoReflect.Descriptor instead.
func (*HealthCheckReq) Descriptor() ([]byte, []int) {
	return file_avatar_proto_rawDescGZIP(), []int{6}
}

type HealthCheckRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRsp) Reset() {
	*x = HealthCheckRsp{}
	mi := &file_avatar_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRsp) ProtoMessage() {}

func (x *HealthCheckRsp) ProtoReflect() protoreflect.Message {
	mi := &file_avatar_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRsp.ProtoReflect.Descriptor instead.
func (*HealthCheckRsp) Descriptor() ([]byte, []int) {
	return file_avatar_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckRsp) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckRsp) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_avatar_proto protoreflect.FileDescriptor

const file_avatar_proto_rawDesc = "" +
	"\n" +
	"\favatar.proto\x12\x06avatar\"1\n" +
	"\tCommonRsp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"[\n" +
	"\tUploadReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"image_data\x18\x02 \x01(\fR\timageData\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\"_\n" +
	"\tUploadRsp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\"$\n" +
	"\tDeleteReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"$\n" +
	"\tGetUrlReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"_\n" +
	"\tGetUrlRsp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\"\x10\n" +
	"\x0eHealthCheckReq\"D\n" +
	"\x0eHealthCheckRsp\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion2\xde\x01\n" +
	"\rAvatarService\x12.\n" +
	"\x06Upload\x12\x11.avatar.UploadReq\x1a\x11.avatar.UploadRsp\x12.\n" +
	"\x06Delete\x12\x11.avatar.DeleteReq\x1a\x11.avatar.CommonRsp\x12.\n" +
	"\x06GetUrl\x12\x11.avatar.GetUrlReq\x1a\x11.avatar.GetUrlRsp\x12=\n" +
	"\vHealthCheck\x12\x16.avatar.HealthCheckReq\x1a\x16.avatar.HealthCheckRspB\x16Z\x14GoImageServer/pkg/pbb\x06proto3"

var (
	file_avatar_proto_rawDescOnce sync.Once
	file_avatar_proto_rawDescData []byte
)

func file_avatar_proto_rawDescGZIP() []byte {
	file_avatar_proto_rawDescOnce.Do(func() {
		file_avatar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_avatar_proto_rawDesc), len(file_avatar_proto_rawDesc)))
	})
	return file_avatar_proto_rawDescData
}

var file_avatar_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_avatar_proto_goTypes = []any{
	(*CommonRsp)(nil),      // 0: avatar.CommonRsp
	(*UploadReq)(nil),      // 1: avatar.UploadReq
	(*UploadRsp)(nil),      // 2: avatar.UploadRsp
	(*DeleteReq)(nil),      // 3: avatar.DeleteReq
	(*GetUrlReq)(nil),      // 4: avatar.GetUrlReq
	(*GetUrlRsp)(nil),      // 5: avatar.GetUrlRsp
	(*HealthCheckReq)(nil), // 6: avatar.HealthCheckReq
	(*HealthCheckRsp)(nil), // 7: avatar.HealthCheckRsp
}
var file_avatar_proto_depIdxs = []int32{
	1, // 0: avatar.AvatarService.Upload:input_type -> avatar.UploadReq
	3, // 1: avatar.AvatarService.Delete:input_type -> avatar.DeleteReq
	4, // 2: avatar.AvatarService.GetUrl:input_type -> avatar.GetUrlReq
	6, // 3: avatar.AvatarService.HealthCheck:input_type -> avatar.HealthCheckReq
	2, // 4: avatar.AvatarService.Upload:output_type -> avatar.UploadRsp
	0, // 5: avatar.AvatarService.Delete:output_type -> avatar.CommonRsp
	5, // 6: avatar.AvatarService.GetUrl:output_type -> avatar.GetUrlRsp
	7, // 7: avatar.AvatarService.HealthCheck:output_type -> avatar.HealthCheckRsp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_avatar_proto_init() }
func file_avatar_proto_init() {
	if File_avatar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_avatar_proto_rawDesc), len(file_avatar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_avatar_proto_goTypes,
		DependencyIndexes: file_avatar_proto_depIdxs,
		MessageInfos:      file_avatar_proto_msgTypes,
	}.Build()
	File_avatar_proto = out.File
	file_avatar_proto_goTypes = nil
	file_avatar_proto_depIdxs = nil
}
